"""
Static data for the Tainment+ music system.
No discord imports — pure data used by music_discovery, music_trivia, music_profiles.
"""

GENRE_LIST = ['pop', 'hiphop', 'rock', 'electronic', 'rnb', 'jazz', 'country', 'latin', 'indie', 'soul', 'reggae', 'classical', 'metal', 'folk', 'kpop', 'lofi']
MOOD_LIST   = ['hype', 'chill', 'sad', 'focus', 'party', 'workout']

# ── Trivia Questions ──────────────────────────────────────────────────────────
# Each entry: {'q': str, 'a': str, 'options': [correct, wrong1, wrong2, wrong3]}

TRIVIA_QUESTIONS = {
    'pop': [
        {'q': 'Which artist released the album "1989"?', 'a': 'Taylor Swift', 'options': ['Taylor Swift', 'Ariana Grande', 'Dua Lipa', 'Katy Perry']},
        {'q': 'What is the real name of the artist known as "The Weeknd"?', 'a': 'Abel Tesfaye', 'options': ['Abel Tesfaye', 'Michael Buble', 'Drake Graham', 'Justin Bieber']},
        {'q': 'Which pop star\'s album was called "Lemonade"?', 'a': 'Beyonce', 'options': ['Beyonce', 'Rihanna', 'Mariah Carey', 'Alicia Keys']},
        {'q': 'Which artist sang "Bad Guy"?', 'a': 'Billie Eilish', 'options': ['Billie Eilish', 'Olivia Rodrigo', 'Halsey', 'Lorde']},
        {'q': '"Shape of You" was a massive hit for which artist?', 'a': 'Ed Sheeran', 'options': ['Ed Sheeran', 'Sam Smith', 'Harry Styles', 'Charlie Puth']},
        {'q': 'Which artist is known as "Queen of Pop"?', 'a': 'Madonna', 'options': ['Madonna', 'Whitney Houston', 'Mariah Carey', 'Celine Dion']},
        {'q': 'Olivia Rodrigo\'s debut album was called what?', 'a': 'SOUR', 'options': ['SOUR', 'SWEET', 'BITTER', 'SALT']},
        {'q': '"Levitating" is a song by which artist?', 'a': 'Dua Lipa', 'options': ['Dua Lipa', 'Ava Max', 'Doja Cat', 'Lizzo']},
        {'q': 'Who sang "Blinding Lights"?', 'a': 'The Weeknd', 'options': ['The Weeknd', 'Post Malone', 'Bruno Mars', 'Justin Timberlake']},
        {'q': 'Which boyband sang "Watermelon Sugar"?', 'a': 'Harry Styles (solo)', 'options': ['Harry Styles (solo)', 'One Direction', 'BTS', 'Jonas Brothers']},
        {'q': 'Who released the album "Future Nostalgia"?', 'a': 'Dua Lipa', 'options': ['Dua Lipa', 'Cardi B', 'Megan Thee Stallion', 'Normani']},
        {'q': '"drivers license" was released by which artist?', 'a': 'Olivia Rodrigo', 'options': ['Olivia Rodrigo', 'Sabrina Carpenter', 'Madison Beer', 'Conan Gray']},
        {'q': 'Which artist sang "As It Was"?', 'a': 'Harry Styles', 'options': ['Harry Styles', 'Ed Sheeran', 'Shawn Mendes', 'Niall Horan']},
        {'q': 'Ariana Grande\'s "thank u, next" is about what?', 'a': 'Her exes', 'options': ['Her exes', 'Her friends', 'Her career', 'Her family']},
        {'q': 'What year did "Gangnam Style" go viral?', 'a': '2012', 'options': ['2012', '2010', '2013', '2014']},
    ],
    'hiphop': [
        {'q': 'Which rapper\'s real name is Aubrey Graham?', 'a': 'Drake', 'options': ['Drake', 'Lil Wayne', 'Kanye West', 'Jay-Z']},
        {'q': 'Kendrick Lamar won a Pulitzer Prize for which album?', 'a': 'DAMN.', 'options': ['DAMN.', 'good kid m.A.A.d city', 'To Pimp a Butterfly', 'Section.80']},
        {'q': 'Which city is Cardi B from?', 'a': 'New York', 'options': ['New York', 'Atlanta', 'Los Angeles', 'Miami']},
        {'q': '"Sicko Mode" features which two rappers?', 'a': 'Travis Scott & Drake', 'options': ['Travis Scott & Drake', 'Post Malone & Drake', 'Future & Drake', 'Lil Uzi & Travis Scott']},
        {'q': 'Jay-Z and Beyonce\'s joint album is titled?', 'a': 'Everything Is Love', 'options': ['Everything Is Love', 'On The Run', 'Watch The Throne', 'Lemonade']},
        {'q': 'Which rapper released "Astroworld"?', 'a': 'Travis Scott', 'options': ['Travis Scott', 'Playboi Carti', 'Young Thug', 'Gunna']},
        {'q': 'Eminem\'s real name is?', 'a': 'Marshall Mathers', 'options': ['Marshall Mathers', 'James Smith', 'Robert Trujillo', 'Kevin Gates']},
        {'q': '"God\'s Plan" is by which rapper?', 'a': 'Drake', 'options': ['Drake', 'Post Malone', 'Lil Baby', 'Roddy Ricch']},
        {'q': 'Which city is known as the birthplace of hip hop?', 'a': 'New York City', 'options': ['New York City', 'Compton', 'Atlanta', 'Chicago']},
        {'q': 'Nicki Minaj is originally from which country?', 'a': 'Trinidad and Tobago', 'options': ['Trinidad and Tobago', 'Jamaica', 'Barbados', 'Guyana']},
        {'q': '"Humble" is a hit song by which rapper?', 'a': 'Kendrick Lamar', 'options': ['Kendrick Lamar', 'J. Cole', 'Logic', 'Big Sean']},
        {'q': 'Which rapper is known as "Weezy F. Baby"?', 'a': 'Lil Wayne', 'options': ['Lil Wayne', 'Lil Uzi Vert', 'Lil Pump', 'Lil Baby']},
        {'q': 'Megan Thee Stallion is from which city?', 'a': 'Houston', 'options': ['Houston', 'Dallas', 'Atlanta', 'Detroit']},
        {'q': '"Lose Yourself" is from which movie?', 'a': '8 Mile', 'options': ['8 Mile', 'Straight Outta Compton', 'Hustle', 'Space Jam']},
        {'q': 'Which rapper\'s debut album was "Cole World: The Sideline Story"?', 'a': 'J. Cole', 'options': ['J. Cole', 'Big K.R.I.T.', 'Wale', 'Kid Cudi']},
    ],
    'rock': [
        {'q': 'Which band sang "Bohemian Rhapsody"?', 'a': 'Queen', 'options': ['Queen', 'Led Zeppelin', 'The Rolling Stones', 'Aerosmith']},
        {'q': '"Smells Like Teen Spirit" is by which band?', 'a': 'Nirvana', 'options': ['Nirvana', 'Pearl Jam', 'Soundgarden', 'Alice in Chains']},
        {'q': 'Which rock band is known as "The Fab Four"?', 'a': 'The Beatles', 'options': ['The Beatles', 'The Rolling Stones', 'The Who', 'Led Zeppelin']},
        {'q': 'AC/DC\'s lead singer for most of their career was?', 'a': 'Brian Johnson', 'options': ['Brian Johnson', 'Bon Scott', 'Robert Plant', 'Roger Daltrey']},
        {'q': 'Which band released "Hotel California"?', 'a': 'Eagles', 'options': ['Eagles', 'Fleetwood Mac', 'The Doobie Brothers', 'Crosby Stills & Nash']},
        {'q': 'Kurt Cobain was the frontman of which band?', 'a': 'Nirvana', 'options': ['Nirvana', 'Pearl Jam', 'Hole', 'Soundgarden']},
        {'q': '"Back in Black" is an album by which band?', 'a': 'AC/DC', 'options': ['AC/DC', 'Black Sabbath', 'Def Leppard', 'Motley Crue']},
        {'q': 'Which band sang "Sweet Child O\' Mine"?', 'a': "Guns N' Roses", 'options': ["Guns N' Roses", 'Motley Crue', 'Whitesnake', 'Bon Jovi']},
        {'q': 'Freddie Mercury was the lead singer of which band?', 'a': 'Queen', 'options': ['Queen', 'David Bowie\'s band', 'Elton John Band', 'Rod Stewart Band']},
        {'q': '"Master of Puppets" is a famous album by which band?', 'a': 'Metallica', 'options': ['Metallica', 'Slayer', 'Megadeth', 'Anthrax']},
        {'q': 'Which British band released "Wonderwall"?', 'a': 'Oasis', 'options': ['Oasis', 'Blur', 'Radiohead', 'The Verve']},
        {'q': '"Stairway to Heaven" is by which band?', 'a': 'Led Zeppelin', 'options': ['Led Zeppelin', 'Deep Purple', 'Black Sabbath', 'Cream']},
        {'q': 'The Red Hot Chili Peppers are from which city?', 'a': 'Los Angeles', 'options': ['Los Angeles', 'San Francisco', 'Seattle', 'New York']},
        {'q': 'Linkin Park\'s debut album is called?', 'a': 'Hybrid Theory', 'options': ['Hybrid Theory', 'Meteora', 'Minutes to Midnight', 'A Thousand Suns']},
        {'q': 'Which band sang "Mr. Brightside"?', 'a': 'The Killers', 'options': ['The Killers', 'Arctic Monkeys', 'Interpol', 'Franz Ferdinand']},
    ],
    'electronic': [
        {'q': 'Daft Punk is a duo from which country?', 'a': 'France', 'options': ['France', 'Germany', 'UK', 'USA']},
        {'q': '"Levels" is a famous track by which DJ?', 'a': 'Avicii', 'options': ['Avicii', 'Calvin Harris', 'Martin Garrix', 'Tiesto']},
        {'q': 'Which artist produced "One More Time"?', 'a': 'Daft Punk', 'options': ['Daft Punk', 'Chemical Brothers', 'Fatboy Slim', 'Basement Jaxx']},
        {'q': '"Animals" is a track by which DJ?', 'a': 'Martin Garrix', 'options': ['Martin Garrix', 'David Guetta', 'Skrillex', 'Diplo']},
        {'q': 'The "EDM" abbreviation stands for?', 'a': 'Electronic Dance Music', 'options': ['Electronic Dance Music', 'Extended Dance Mix', 'Elite DJ Music', 'Euro Dance Movement']},
        {'q': 'Which artist is known as the "Godfather of House"?', 'a': 'Frankie Knuckles', 'options': ['Frankie Knuckles', 'DJ Premier', 'Larry Heard', 'Marshall Jefferson']},
        {'q': '"Scary Monsters and Nice Sprites" is by which artist?', 'a': 'Skrillex', 'options': ['Skrillex', 'Deadmau5', 'Feed Me', 'Borgore']},
        {'q': 'Which city is known as the birthplace of techno music?', 'a': 'Detroit', 'options': ['Detroit', 'Chicago', 'Berlin', 'London']},
        {'q': '"Titanium" features which vocalist?', 'a': 'Sia', 'options': ['Sia', 'Ellie Goulding', 'Lorde', 'Rihanna']},
        {'q': 'Which DJ duo went by the name "Chemical Brothers"?', 'a': 'Tom Rowlands & Ed Simons', 'options': ['Tom Rowlands & Ed Simons', 'Guy-Manuel & Thomas', 'Neil & Rob', 'Ed & Andy']},
        {'q': '"Around the World" is by which duo?', 'a': 'Daft Punk', 'options': ['Daft Punk', 'Basement Jaxx', 'Chemical Brothers', 'Orbital']},
        {'q': 'Calvin Harris is from which country?', 'a': 'Scotland', 'options': ['Scotland', 'England', 'Australia', 'USA']},
        {'q': '"Wake Me Up" was a hit by which artist?', 'a': 'Avicii', 'options': ['Avicii', 'Zedd', 'Kygo', 'Illenium']},
        {'q': 'Which genre originated in Chicago clubs in the 1980s?', 'a': 'House', 'options': ['House', 'Techno', 'Trance', 'Drum and Bass']},
        {'q': '"Strobe" is an iconic track by which artist?', 'a': 'Deadmau5', 'options': ['Deadmau5', 'Eric Prydz', 'Paul van Dyk', 'Armin van Buuren']},
    ],
    'general': [
        {'q': 'What does "BPM" stand for in music?', 'a': 'Beats Per Minute', 'options': ['Beats Per Minute', 'Bass Play Mode', 'Beat Pattern Measure', 'Base Pulse Meter']},
        {'q': 'How many strings does a standard guitar have?', 'a': '6', 'options': ['6', '4', '8', '12']},
        {'q': 'Which instrument has 88 keys?', 'a': 'Piano', 'options': ['Piano', 'Organ', 'Harpsichord', 'Synthesizer']},
        {'q': 'What is the speed of a song called?', 'a': 'Tempo', 'options': ['Tempo', 'Rhythm', 'Pitch', 'Timbre']},
        {'q': 'A "vinyl" is another name for a what?', 'a': 'Record', 'options': ['Record', 'CD', 'Cassette', 'Reel']},
        {'q': 'Which music streaming service launched in 2008?', 'a': 'Spotify', 'options': ['Spotify', 'Apple Music', 'Tidal', 'Deezer']},
        {'q': 'What is a group of two musicians called?', 'a': 'Duo', 'options': ['Duo', 'Trio', 'Quartet', 'Ensemble']},
        {'q': 'Which note comes after G in the musical alphabet?', 'a': 'A', 'options': ['A', 'H', 'B', 'C']},
        {'q': 'What is the lowest male voice type in classical music?', 'a': 'Bass', 'options': ['Bass', 'Baritone', 'Tenor', 'Alto']},
        {'q': 'The Grammy Awards were first held in which year?', 'a': '1959', 'options': ['1959', '1970', '1965', '1975']},
        {'q': 'Which instrument is Yo-Yo Ma famous for playing?', 'a': 'Cello', 'options': ['Cello', 'Violin', 'Viola', 'Double Bass']},
        {'q': 'What does "forte" mean in music?', 'a': 'Loud', 'options': ['Loud', 'Soft', 'Fast', 'Slow']},
        {'q': 'How many beats are in a 4/4 time signature per bar?', 'a': '4', 'options': ['4', '3', '6', '2']},
        {'q': 'Which is the highest female vocal range?', 'a': 'Soprano', 'options': ['Soprano', 'Alto', 'Mezzo-soprano', 'Contralto']},
        {'q': 'What does "a cappella" mean?', 'a': 'Without instrumental accompaniment', 'options': ['Without instrumental accompaniment', 'With full orchestra', 'In a chapel', 'Very slowly']},
    ],
}

# ── Lyric Snippets (for t!namethetune / t!lyricsguess) ───────────────────────
# Partial lyrics only — no full verses, just enough to guess from

LYRIC_SNIPPETS = [
    {'lyrics': 'I knew you were trouble when you walked in\nShame on me now...', 'title': 'I Knew You Were Trouble', 'artist': 'Taylor Swift', 'genre': 'pop'},
    {'lyrics': 'Is it too late now to say sorry\nCause I\'m missing more than just your body...', 'title': 'Sorry', 'artist': 'Justin Bieber', 'genre': 'pop'},
    {'lyrics': 'I came in like a wrecking ball\nI never hit so hard in love...', 'title': 'Wrecking Ball', 'artist': 'Miley Cyrus', 'genre': 'pop'},
    {'lyrics': 'We found love in a hopeless place\nWe found love in a hopeless place...', 'title': 'We Found Love', 'artist': 'Rihanna', 'genre': 'pop'},
    {'lyrics': 'Rolling in the deep\nYou had my heart inside of your hand...', 'title': 'Rolling in the Deep', 'artist': 'Adele', 'genre': 'pop'},
    {'lyrics': "Baby I'm just gonna shake shake shake\nShake it off, shake it off...", 'title': 'Shake It Off', 'artist': 'Taylor Swift', 'genre': 'pop'},
    {'lyrics': "I got one less problem without ya\nI got one less problem without ya...", 'title': 'Problem', 'artist': 'Ariana Grande', 'genre': 'pop'},
    {'lyrics': 'It\'s been a while since I came around\nBeen a long time but I\'m back in town...', 'title': 'Somebody That I Used to Know', 'artist': 'Gotye', 'genre': 'pop'},
    {'lyrics': "You give me that feeling\nEvery time you walk into the room...", 'title': 'Feelings', 'artist': 'Maroon 5', 'genre': 'pop'},
    {'lyrics': 'Started from the bottom now we here\nStarted from the bottom now my whole team here...', 'title': 'Started from the Bottom', 'artist': 'Drake', 'genre': 'hiphop'},
    {'lyrics': "Sit down, be humble\nSit down on what, sit down...be humble...", 'title': 'HUMBLE.', 'artist': 'Kendrick Lamar', 'genre': 'hiphop'},
    {'lyrics': "I just wanna be successful\nI just wanna be...I just wanna be successful...", 'title': 'Successful', 'artist': 'Drake', 'genre': 'hiphop'},
    {'lyrics': 'Real friends, how many of us\nHow many of us, how many jealous...', 'title': 'Real Friends', 'artist': 'Kanye West', 'genre': 'hiphop'},
    {'lyrics': 'Started out local but thanks to all the haters\nI know G4 Pilots on a first name basis...', 'title': 'We Made It', 'artist': 'Drake', 'genre': 'hiphop'},
    {'lyrics': "I lose my mind sometimes\nTill I can't even think straight...", 'title': 'Numb', 'artist': 'Linkin Park', 'genre': 'rock'},
    {'lyrics': 'Hello darkness my old friend\nI\'ve come to talk with you again...', 'title': 'The Sound of Silence', 'artist': 'Simon & Garfunkel', 'genre': 'rock'},
    {'lyrics': "I can't stop this feeling, deep inside of me\nGirl you just don't realize what you do to me...", 'title': 'I Feel Good', 'artist': 'James Brown', 'genre': 'rnb'},
    {'lyrics': "In the night I hear 'em talk\nThe coldest story ever told...", 'title': 'The Hills', 'artist': 'The Weeknd', 'genre': 'rnb'},
    {'lyrics': "Around the world, around the world\nAround the world, around the world...", 'title': 'Around the World', 'artist': 'Daft Punk', 'genre': 'electronic'},
    {'lyrics': "One more time, we're gonna celebrate\nOh yeah, all right, don't stop the dancing...", 'title': 'One More Time', 'artist': 'Daft Punk', 'genre': 'electronic'},
    {'lyrics': "What is love, oh baby don't hurt me\nDon't hurt me, no more...", 'title': 'What Is Love', 'artist': 'Haddaway', 'genre': 'electronic'},
    {'lyrics': "You're gonna hear me roar\nLouder, louder than a lion...", 'title': 'Roar', 'artist': 'Katy Perry', 'genre': 'pop'},
    {'lyrics': "Never gonna give you up\nNever gonna let you down...", 'title': 'Never Gonna Give You Up', 'artist': 'Rick Astley', 'genre': 'pop'},
    {'lyrics': "Sweet dreams are made of this\nWho am I to disagree...", 'title': 'Sweet Dreams', 'artist': 'Eurythmics', 'genre': 'pop'},
    {'lyrics': "Don't you worry child\nSee heaven's got a plan for you...", 'title': "Don't You Worry Child", 'artist': 'Swedish House Mafia', 'genre': 'electronic'},
    {'lyrics': "We will, we will rock you\nWe will, we will rock you...", 'title': 'We Will Rock You', 'artist': 'Queen', 'genre': 'rock'},
    {'lyrics': "I want to break free\nI want to break free from your lies...", 'title': 'I Want to Break Free', 'artist': 'Queen', 'genre': 'rock'},
    {'lyrics': "Cause we are the champions my friends\nAnd we'll keep on fighting till the end...", 'title': 'We Are the Champions', 'artist': 'Queen', 'genre': 'rock'},
    {'lyrics': "I feel the earth move under my feet\nI feel the sky tumbling down...", 'title': 'I Feel the Earth Move', 'artist': 'Carole King', 'genre': 'pop'},
    {'lyrics': "Just a small town girl\nLiving in a lonely world...", 'title': "Don't Stop Believin'", 'artist': 'Journey', 'genre': 'rock'},
]

# ── Song Recommendations ──────────────────────────────────────────────────────

SONG_RECOMMENDATIONS = {
    'pop': [
        {'title': 'As It Was', 'artist': 'Harry Styles', 'description': 'Upbeat indie-pop with emotional undertones about moving forward'},
        {'title': 'Levitating', 'artist': 'Dua Lipa', 'description': 'Disco-pop banger with infectious hooks and retro vibes'},
        {'title': 'Blinding Lights', 'artist': 'The Weeknd', 'description': '80s-inspired synth-pop anthem that dominated charts worldwide'},
        {'title': 'drivers license', 'artist': 'Olivia Rodrigo', 'description': 'Emotional breakup ballad that broke streaming records'},
        {'title': 'Good 4 U', 'artist': 'Olivia Rodrigo', 'description': 'Pop-punk energy with angsty lyrics about moving on'},
        {'title': 'Bad Guy', 'artist': 'Billie Eilish', 'description': 'Minimalist bass-heavy pop with playful dark tone'},
        {'title': 'Shape of You', 'artist': 'Ed Sheeran', 'description': 'Tropical pop groove about attraction and connection'},
        {'title': 'Stay', 'artist': 'The Kid LAROI & Justin Bieber', 'description': 'High-energy pop-rock with a catchy impossible-to-forget hook'},
        {'title': 'Heat Waves', 'artist': 'Glass Animals', 'description': 'Dream-pop track that built slowly into a global hit'},
        {'title': 'Anti-Hero', 'artist': 'Taylor Swift', 'description': 'Self-aware synth-pop about anxiety and self-perception'},
        {'title': 'Flowers', 'artist': 'Miley Cyrus', 'description': 'Empowering pop anthem about self-love after heartbreak'},
        {'title': 'Unholy', 'artist': 'Sam Smith & Kim Petras', 'description': 'Dark cabaret-pop with an irresistible earworm chorus'},
    ],
    'hiphop': [
        {'title': 'HUMBLE.', 'artist': 'Kendrick Lamar', 'description': 'Hard-hitting rap with Mike WiLL production and iconic visuals'},
        {'title': 'Gods Plan', 'artist': 'Drake', 'description': 'Smooth trap with Drake at his most charitable'},
        {'title': 'Rockstar', 'artist': 'Post Malone ft. 21 Savage', 'description': 'Emo-rap crossover that defined late 2010s hip hop sound'},
        {'title': 'Sicko Mode', 'artist': 'Travis Scott ft. Drake', 'description': 'Multi-part banger with three distinct beat switches'},
        {'title': 'WAP', 'artist': 'Cardi B ft. Megan Thee Stallion', 'description': 'Confident female rap anthem that shook the internet'},
        {'title': 'Savage', 'artist': 'Megan Thee Stallion ft. Beyonce', 'description': 'Fierce Houston rap brought to another level by Beyonce'},
        {'title': 'Life Is Good', 'artist': 'Future ft. Drake', 'description': 'Easy-going flex rap with a feel-good summer vibe'},
        {'title': 'Essence', 'artist': 'Wizkid ft. Tems', 'description': 'Afrobeats-infused R&B crossover with hypnotic vocals'},
        {'title': 'Rich Flex', 'artist': 'Drake & 21 Savage', 'description': 'Trap collaboration with iconic call-and-response hook'},
        {'title': 'Family Ties', 'artist': 'Baby Keem & Kendrick Lamar', 'description': 'West Coast rap excellence with two generations linking up'},
        {'title': 'INDUSTRY BABY', 'artist': 'Lil Nas X ft. Jack Harlow', 'description': 'Bold trap-pop crossover with a triumphant brass section'},
        {'title': 'Dynamite', 'artist': 'BTS', 'description': 'Upbeat English-language K-pop that crossed all barriers'},
    ],
    'rock': [
        {'title': 'Mr. Brightside', 'artist': 'The Killers', 'description': 'Indie rock classic about jealousy that never left the charts'},
        {'title': 'Bohemian Rhapsody', 'artist': 'Queen', 'description': 'Operatic rock epic that defied every genre convention'},
        {'title': 'Smells Like Teen Spirit', 'artist': 'Nirvana', 'description': 'Grunge anthem that defined a generation of alternative rock'},
        {'title': 'Welcome to the Black Parade', 'artist': 'My Chemical Romance', 'description': 'Theatrical emo-rock epic with massive emotional impact'},
        {'title': 'Numb', 'artist': 'Linkin Park', 'description': 'Nu-metal/alternative crossover about feeling misunderstood'},
        {'title': 'Somebody That I Used to Know', 'artist': 'Gotye ft. Kimbra', 'description': 'Indie pop-rock breakup song with a distinctive xylophone riff'},
        {'title': 'Seven Nation Army', 'artist': 'The White Stripes', 'description': 'Minimalist garage rock with one of the most iconic riffs ever'},
        {'title': 'Do I Wanna Know?', 'artist': 'Arctic Monkeys', 'description': 'Brooding indie rock with a hypnotic guitar riff'},
        {'title': 'Knights of Cydonia', 'artist': 'Muse', 'description': 'Space-rock epic with spaghetti western influences'},
        {'title': 'Hysteria', 'artist': 'Muse', 'description': 'Bass-driven alternative rock with progressive elements'},
        {'title': 'The Adults Are Talking', 'artist': 'The Strokes', 'description': 'Jangly indie rock comeback from New York legends'},
        {'title': 'Reptilia', 'artist': 'The Strokes', 'description': 'Raw garage rock energy distilled into a perfect 3 minutes'},
    ],
    'electronic': [
        {'title': 'One More Time', 'artist': 'Daft Punk', 'description': 'House anthem built on pitched-up vocals and irresistible groove'},
        {'title': 'Levels', 'artist': 'Avicii', 'description': 'Progressive house classic that launched a generation of EDM'},
        {'title': 'Animals', 'artist': 'Martin Garrix', 'description': 'Big room house track that made a teenage DJ a superstar'},
        {'title': 'Titanium', 'artist': 'David Guetta ft. Sia', 'description': 'Anthemic electro house with soaring Sia vocals'},
        {'title': 'Wake Me Up', 'artist': 'Avicii ft. Aloe Blacc', 'description': 'Folk-electronic fusion that crossed every genre boundary'},
        {'title': 'Lean On', 'artist': 'Major Lazer ft. MO', 'description': 'Global pop-electronic smash with dancehall influence'},
        {'title': "Don't You Worry Child", 'artist': 'Swedish House Mafia', 'description': 'Emotional progressive house farewell from a legendary trio'},
        {'title': 'Turn Down for What', 'artist': 'DJ Snake & Lil Jon', 'description': 'High-energy trap-electronic banger built for the club'},
        {'title': 'Clarity', 'artist': 'Zedd ft. Foxes', 'description': 'Electro house with orchestral elements and a cinematic drop'},
        {'title': 'Midnight City', 'artist': "M83", 'description': 'Dreamy synth-pop with a saxophone solo you will never forget'},
        {'title': 'Ocean Drive', 'artist': 'Duke Dumont', 'description': 'Melancholic deep house with a nostalgic summer feel'},
        {'title': 'Strobe', 'artist': 'Deadmau5', 'description': 'Progressive house masterpiece with a 10-minute slow build'},
    ],
    'rnb': [
        {'title': 'Essence', 'artist': 'Wizkid ft. Tems', 'description': 'Smooth Afrobeats-R&B blend that swept global charts'},
        {'title': 'STAY', 'artist': 'Rihanna ft. Mikky Ekko', 'description': 'Stripped-back ballad showing a vulnerable side of Rihanna'},
        {'title': 'Blinding Lights', 'artist': 'The Weeknd', 'description': 'Synth-pop influenced R&B with cinematic nighttime energy'},
        {'title': 'Leave the Door Open', 'artist': 'Silk Sonic', 'description': 'Classic soul-R&B from Bruno Mars and Anderson .Paak'},
        {'title': 'Location', 'artist': 'Khalid', 'description': 'Laid-back teen R&B with honest lyrics about young love'},
        {'title': 'Peaches', 'artist': 'Justin Bieber ft. Daniel Caesar & Giveon', 'description': 'Smooth R&B about appreciating blessings in life'},
        {'title': 'Die For You', 'artist': 'The Weeknd', 'description': 'Emotional 80s-influenced R&B about intense devotion'},
        {'title': 'All of Me', 'artist': 'John Legend', 'description': 'Piano-driven love ballad that became a wedding staple'},
    ],
    'jazz': [
        {'title': 'Take Five', 'artist': 'Dave Brubeck Quartet', 'description': 'Jazz standard in unusual 5/4 time — a true classic'},
        {'title': "So What", 'artist': 'Miles Davis', 'description': 'Modal jazz opener from Kind of Blue — pure cool sophistication'},
        {'title': 'Autumn Leaves', 'artist': 'Bill Evans', 'description': 'Melancholic jazz piano interpretation of a beloved standard'},
        {'title': 'Round Midnight', 'artist': 'Thelonious Monk', 'description': 'Late-night jazz with Monk\'s distinctive angular style'},
        {'title': "Feeling Good", 'artist': 'Nina Simone', 'description': 'Soul-jazz powerhouse vocal performance about liberation'},
        {'title': 'My Favorite Things', 'artist': 'John Coltrane', 'description': "Coltrane's soprano sax reimagining of the Broadway tune"},
        {'title': 'A Love Supreme', 'artist': 'John Coltrane', 'description': 'Four-part spiritual jazz suite and a defining masterpiece'},
        {'title': 'Fly Me to the Moon', 'artist': 'Frank Sinatra', 'description': 'Swinging jazz standard about romantic longing'},
    ],
    'country': [
        {'title': 'Jolene', 'artist': 'Dolly Parton', 'description': 'Iconic country plea with one of the most memorable opening riffs'},
        {'title': 'Old Town Road', 'artist': 'Lil Nas X ft. Billy Ray Cyrus', 'description': 'Country-trap crossover that broke every chart record'},
        {'title': 'Before He Cheats', 'artist': 'Carrie Underwood', 'description': 'Fiery country anthem about revenge and self-respect'},
        {'title': 'Friends in Low Places', 'artist': 'Garth Brooks', 'description': 'Beloved crowd-sing-along classic about moving on'},
        {'title': 'Tennessee Whiskey', 'artist': 'Chris Stapleton', 'description': 'Soulful country ballad with bluegrass roots'},
        {'title': 'Take Me Home, Country Roads', 'artist': 'John Denver', 'description': 'Nostalgic folk-country ode to West Virginia'},
        {'title': 'Wagon Wheel', 'artist': 'Darius Rucker', 'description': 'Modern country staple built on an old Bob Dylan melody'},
        {'title': 'Cruise', 'artist': 'Florida Georgia Line', 'description': 'Bro-country summer hit that defined a genre era'},
        {'title': 'Ring of Fire', 'artist': 'Johnny Cash', 'description': 'Mariachi-tinged classic from the Man in Black'},
        {'title': 'Body Like a Back Road', 'artist': 'Sam Hunt', 'description': 'Country-pop crossover with a laid-back summer groove'},
        {'title': 'Need You Now', 'artist': 'Lady Antebellum', 'description': 'Late-night country duet that swept the Grammy stage'},
        {'title': 'Die a Happy Man', 'artist': 'Thomas Rhett', 'description': 'Heartfelt country ballad about love and gratitude'},
    ],
    'latin': [
        {'title': 'Despacito', 'artist': 'Luis Fonsi ft. Daddy Yankee', 'description': 'Reggaeton-pop that became the most streamed song ever at the time'},
        {'title': 'Con Calma', 'artist': 'Daddy Yankee & Snow', 'description': 'Dancehall-reggaeton fusion with nostalgic nineties roots'},
        {'title': 'Hawai', 'artist': 'Maluma', 'description': 'Slick reggaeton about longing for an ex during lockdown'},
        {'title': 'China', 'artist': 'Anuel AA ft. Daddy Yankee', 'description': 'Heavy-hitting trap-reggaeton collab from Latin heavyweights'},
        {'title': 'Taki Taki', 'artist': 'DJ Snake ft. Selena Gomez, Ozuna & Cardi B', 'description': 'Global Latin-electronic collaboration with massive crossover appeal'},
        {'title': 'Con Altura', 'artist': 'ROSALÍA ft. J Balvin', 'description': 'Flamenco-infused reggaeton pushing the genre forward'},
        {'title': 'Bad Guy (Remix)', 'artist': 'Nicky Jam ft. Bad Bunny', 'description': 'Latin trap spin on the Billie Eilish hit'},
        {'title': 'Reggaeton en lo Oscuro', 'artist': 'Daddy Yankee', 'description': 'Club-ready reggaeton from the genre\'s reigning king'},
        {'title': 'Si Tu Novio Te Deja Sola', 'artist': 'J Balvin ft. Bad Bunny', 'description': 'Party-starters from two Colombian powerhouses'},
        {'title': 'Conga', 'artist': 'Gloria Estefan', 'description': 'Classic Latin pop crossover built for dancing'},
        {'title': 'Smooth', 'artist': 'Santana ft. Rob Thomas', 'description': 'Latin rock groove with iconic guitar and mainstream appeal'},
        {'title': 'Livin la Vida Loca', 'artist': 'Ricky Martin', 'description': 'The song that launched the Latin pop explosion of the 90s'},
    ],
    'indie': [
        {'title': 'Mr. Brightside', 'artist': 'The Killers', 'description': 'Indie rock classic that never left the UK charts for years'},
        {'title': 'Do I Wanna Know?', 'artist': 'Arctic Monkeys', 'description': 'Brooding Sheffield indie with one of the most hypnotic riffs ever'},
        {'title': 'Electric Feel', 'artist': 'MGMT', 'description': 'Psychedelic indie-pop that perfectly captures late-night energy'},
        {'title': 'Take a Walk', 'artist': 'Passion Pit', 'description': 'Upbeat synth-indie with surprisingly dark lyrical content'},
        {'title': 'Little Talks', 'artist': 'Of Monsters and Men', 'description': 'Icelandic indie folk with gorgeous male-female harmonies'},
        {'title': 'Ho Hey', 'artist': 'The Lumineers', 'description': 'Stomping indie folk anthem about belonging and longing'},
        {'title': '505', 'artist': 'Arctic Monkeys', 'description': 'Cinematic indie closer that builds from quiet to devastating'},
        {'title': 'Ribs', 'artist': 'Lorde', 'description': 'Introspective bedroom pop about the terror of growing up'},
        {'title': 'Sweater Weather', 'artist': 'The Neighbourhood', 'description': 'Moody indie pop with a nostalgic autumn atmosphere'},
        {'title': 'Stubborn Love', 'artist': 'The Lumineers', 'description': 'Quietly powerful folk-indie about persisting through pain'},
        {'title': 'Time to Pretend', 'artist': 'MGMT', 'description': 'Satirical indie anthem about rockstar fantasy versus reality'},
        {'title': 'Budapest', 'artist': 'George Ezra', 'description': 'Warm indie folk declaration of all-consuming love'},
    ],
    'soul': [
        {'title': "Feeling Good", 'artist': 'Nina Simone', 'description': 'Transcendent vocal performance about freedom and liberation'},
        {'title': 'Respect', 'artist': 'Aretha Franklin', 'description': 'The defining soul anthem demanding dignity and recognition'},
        {'title': "I Got You (I Feel Good)", 'artist': 'James Brown', 'description': 'The Godfather of Soul at his most exuberant and energetic'},
        {'title': 'A Change Is Gonna Come', 'artist': 'Sam Cooke', 'description': 'Civil rights-era soul ballad of hope and perseverance'},
        {'title': "Let's Stay Together", 'artist': 'Al Green', 'description': 'Smooth southern soul about commitment and devotion'},
        {'title': 'What\'s Going On', 'artist': 'Marvin Gaye', 'description': 'Socially conscious soul masterpiece ahead of its time'},
        {'title': 'Superstition', 'artist': 'Stevie Wonder', 'description': 'Funk-soul classic driven by an iconic clavinet riff'},
        {'title': 'Leave the Door Open', 'artist': 'Silk Sonic', 'description': 'Modern soul throwback from Bruno Mars and Anderson .Paak'},
        {'title': 'Golden', 'artist': 'Jill Scott', 'description': 'Neo-soul affirmation of living life on your own terms'},
        {'title': 'Back to Black', 'artist': 'Amy Winehouse', 'description': 'Retro soul heartbreak delivered with stunning raw honesty'},
        {'title': 'No One', 'artist': 'Alicia Keys', 'description': 'Piano-driven neo-soul about unwavering romantic certainty'},
        {'title': 'The Thrill Is Gone', 'artist': 'B.B. King', 'description': 'Blues-soul farewell laced with King\'s legendary guitar tone'},
    ],
    'reggae': [
        {'title': 'No Woman No Cry', 'artist': 'Bob Marley & The Wailers', 'description': 'Gentle reggae comfort from the King of Reggae himself'},
        {'title': 'One Love', 'artist': 'Bob Marley & The Wailers', 'description': 'Universal anthem of unity and peace rooted in Rastafari'},
        {'title': 'Could You Be Loved', 'artist': 'Bob Marley & The Wailers', 'description': 'Upbeat reggae-funk hybrid with a call to love and truth'},
        {'title': 'Redemption Song', 'artist': 'Bob Marley', 'description': 'Acoustic reggae folk hymn about freedom from oppression'},
        {'title': 'The Harder They Come', 'artist': 'Jimmy Cliff', 'description': 'Reggae outlaw anthem that launched the genre globally'},
        {'title': 'Rivers of Babylon', 'artist': 'The Melodians', 'description': 'Roots reggae lament drawn from biblical Psalm 137'},
        {'title': 'Pressure Drop', 'artist': 'Toots and the Maytals', 'description': 'Ska-reggae classic later made famous by The Clash cover'},
        {'title': 'Informer', 'artist': 'Snow', 'description': '90s dancehall-reggae crossover novelty hit impossible to forget'},
        {'title': 'Here I Am (Come and Take Me)', 'artist': 'UB40', 'description': 'British reggae-pop cover that introduced roots to new audiences'},
        {'title': 'Red Red Wine', 'artist': 'UB40', 'description': 'Reggae-pop groove with smooth sailing vibes'},
        {'title': 'Electric Avenue', 'artist': 'Eddy Grant', 'description': 'Dancehall-infused reggae about the Brixton riots'},
        {'title': 'Pass the Dutchie', 'artist': 'Musical Youth', 'description': 'Feel-good roots reggae from the youngest chart-toppers ever'},
    ],
    'classical': [
        {'title': 'Clair de Lune', 'artist': 'Debussy', 'description': 'Impressionist piano masterpiece evoking moonlight and stillness'},
        {'title': 'Symphony No. 9', 'artist': 'Beethoven', 'description': 'Monumental choral symphony including the iconic "Ode to Joy"'},
        {'title': 'Four Seasons — Spring', 'artist': 'Vivaldi', 'description': 'Baroque violin concerto painting the arrival of spring'},
        {'title': 'Moonlight Sonata', 'artist': 'Beethoven', 'description': 'Hauntingly beautiful piano sonata in three movements'},
        {'title': 'Canon in D', 'artist': 'Pachelbel', 'description': 'Timeless baroque piece built on a repeating bass line'},
        {'title': 'Nocturne in E-flat Major', 'artist': 'Chopin', 'description': 'Lyrical Romantic-era piano poem perfect for late evenings'},
        {'title': 'The Blue Danube', 'artist': 'Johann Strauss II', 'description': 'Elegant waltz that defines Viennese orchestral tradition'},
        {'title': 'Gymnopédie No. 1', 'artist': 'Erik Satie', 'description': 'Minimalist piano meditation with dreamlike simplicity'},
        {'title': 'Boléro', 'artist': 'Ravel', 'description': 'Hypnotic single-theme orchestral build over 15 relentless minutes'},
        {'title': 'Toccata and Fugue in D Minor', 'artist': 'Bach', 'description': 'Dramatic organ work — one of the most recognisable classical pieces'},
        {'title': 'Swan Lake Suite', 'artist': 'Tchaikovsky', 'description': 'Lush orchestral ballet score depicting love and transformation'},
        {'title': 'Experience', 'artist': 'Ludovico Einaudi', 'description': 'Contemporary classical piano piece with cinematic emotional depth'},
    ],
    'metal': [
        {'title': 'Master of Puppets', 'artist': 'Metallica', 'description': 'Thrash metal epic about the destructive power of addiction'},
        {'title': 'Paranoid', 'artist': 'Black Sabbath', 'description': 'Proto-metal classic that launched a thousand heavy bands'},
        {'title': 'Raining Blood', 'artist': 'Slayer', 'description': 'Relentless thrash metal pinnacle from Reign in Blood'},
        {'title': 'The Trooper', 'artist': 'Iron Maiden', 'description': 'Galloping heavy metal war anthem with a singalong chorus'},
        {'title': 'Holy Wars... The Punishment Due', 'artist': 'Megadeth', 'description': 'Politically charged thrash metal in two explosive parts'},
        {'title': 'One', 'artist': 'Metallica', 'description': 'Progressive thrash epic moving from quiet despair to full assault'},
        {'title': 'Chop Suey!', 'artist': 'System of a Down', 'description': 'Frenetic nu-metal with dizzying tempo shifts and literary lyrics'},
        {'title': 'Numb', 'artist': 'Linkin Park', 'description': 'Nu-metal crossover hit about identity and parental pressure'},
        {'title': 'Break Stuff', 'artist': 'Limp Bizkit', 'description': 'Cathartic nu-metal venting track beloved at festivals'},
        {'title': 'The Number of the Beast', 'artist': 'Iron Maiden', 'description': 'Classic NWOBHM anthem with Bruce Dickinson\'s iconic scream'},
        {'title': 'Hells Bells', 'artist': 'AC/DC', 'description': 'Hard rock-metal opener built on a mournful tolling bell'},
        {'title': 'Toxicity', 'artist': 'System of a Down', 'description': 'Alternative metal critique of consumerist culture with Armenian influences'},
    ],
    'folk': [
        {'title': 'The Sound of Silence', 'artist': 'Simon & Garfunkel', 'description': 'Haunting acoustic folk about modern isolation and communication'},
        {'title': 'Blowin\' in the Wind', 'artist': 'Bob Dylan', 'description': 'Civil rights folk anthem posing unanswerable questions'},
        {'title': 'The Times They Are A-Changin\'', 'artist': 'Bob Dylan', 'description': 'Call-to-action folk ballad that defined a generation of protest'},
        {'title': 'Fast Car', 'artist': 'Tracy Chapman', 'description': 'Narrative folk-pop about escaping poverty and finding hope'},
        {'title': 'House of the Rising Sun', 'artist': 'The Animals', 'description': 'Haunting folk ballad about a life of sin in New Orleans'},
        {'title': 'Scarborough Fair', 'artist': 'Simon & Garfunkel', 'description': 'Ethereal two-melody counterpoint folk song of lost love'},
        {'title': 'The Boxer', 'artist': 'Simon & Garfunkel', 'description': 'Folk epic about resilience told through a street fighter\'s eyes'},
        {'title': 'California Dreamin\'', 'artist': 'The Mamas & The Papas', 'description': 'Lush folk-pop harmony about longing for warmth in winter'},
        {'title': 'Take Me Home, Country Roads', 'artist': 'John Denver', 'description': 'Beloved folk-country hymn to the mountains of West Virginia'},
        {'title': 'Skinny Love', 'artist': 'Bon Iver', 'description': 'Rawly emotional indie-folk written in isolation in a cabin'},
        {'title': 'Ho Hey', 'artist': 'The Lumineers', 'description': 'Stomp-and-clap folk-pop built for singing around a fire'},
        {'title': 'Dust in the Wind', 'artist': 'Kansas', 'description': 'Acoustic folk-rock meditation on mortality and impermanence'},
    ],
    'kpop': [
        {'title': 'Dynamite', 'artist': 'BTS', 'description': 'BTS\'s first all-English release — disco-pop perfection'},
        {'title': 'Butter', 'artist': 'BTS', 'description': 'Smooth synth-pop built for a global mainstream audience'},
        {'title': 'Kill This Love', 'artist': 'BLACKPINK', 'description': 'Intense K-pop anthem with marching band brass and fierce energy'},
        {'title': 'How You Like That', 'artist': 'BLACKPINK', 'description': 'Cinematic comeback track with explosive production'},
        {'title': 'Likey', 'artist': 'TWICE', 'description': 'Bright K-pop-pop about the anxieties of social media validation'},
        {'title': 'Next Level', 'artist': 'aespa', 'description': 'Genre-blending K-pop with a story about virtual alter-egos'},
        {'title': 'FEVER', 'artist': 'ENHYPEN', 'description': 'Dark concept K-pop about a dangerous, irresistible attraction'},
        {'title': 'Miroh', 'artist': 'Stray Kids', 'description': 'Self-produced K-pop hype track about facing a maze of challenges'},
        {'title': 'Love Shot', 'artist': 'EXO', 'description': 'Suave mid-tempo K-pop with cinematic gunshot sound design'},
        {'title': 'TT', 'artist': 'TWICE', 'description': 'Halloween-themed K-pop banger that defined TWICE\'s early era'},
        {'title': 'Ditto', 'artist': 'NewJeans', 'description': 'Y2K-inspired K-pop with hazy production and youthful nostalgia'},
        {'title': 'Hype Boy', 'artist': 'NewJeans', 'description': 'Effortlessly cool K-pop with a retro-R&B groove'},
    ],
    'lofi': [
        {'title': 'Snowman', 'artist': 'Øneheart & reidenshi', 'description': 'Iconic lo-fi track — serene and melancholic with gentle piano'},
        {'title': 'Clair de Lune (Lo-Fi Remix)', 'artist': 'Various', 'description': 'Classical beauty filtered through vinyl crackle and bedroom beats'},
        {'title': 'Eyes Closed', 'artist': 'Wun Two', 'description': 'Dusty jazz-hop with muted chops and a dreamy floating feel'},
        {'title': 'Through the Night', 'artist': 'Idealism', 'description': 'Lo-fi hip hop perfect for studying late into the evening'},
        {'title': 'Sleepless', 'artist': 'LilyPichu', 'description': 'Soft lo-fi with gentle vocals evoking quiet 3am thoughts'},
        {'title': 'Caramel Latte', 'artist': 'Powfu', 'description': 'Lo-fi bedroom pop with warm acoustic guitar and soft delivery'},
        {'title': 'Death Bed', 'artist': 'Powfu ft. beabadoobee', 'description': 'Fragile lo-fi love song that went viral for its quiet sincerity'},
        {'title': 'Peach', 'artist': 'Kevin Penkin', 'description': 'Ambient lo-fi piano melody with a sunset warmth'},
        {'title': 'Swim', 'artist': 'JVKE', 'description': 'Lo-fi pop with layered piano arpeggios and an emotional core'},
        {'title': 'After the Rain', 'artist': 'HM Surf', 'description': 'Rainy-day lo-fi with field recordings and a meditative mood'},
        {'title': 'Chilled Beats Vol. 1', 'artist': 'Lofi Girl', 'description': 'The iconic YouTube stream that defined lo-fi hip hop culture'},
        {'title': 'Coffee Shop Vibes', 'artist': 'Chillhop Music', 'description': 'Mellow instrumental lo-fi built for focus and calm'},
    ],
}

# ── Mood-Based Recommendations ────────────────────────────────────────────────

MOOD_SONGS = {
    'hype': [
        {'title': 'HUMBLE.', 'artist': 'Kendrick Lamar', 'description': 'Drill the energy into the room'},
        {'title': 'Sicko Mode', 'artist': 'Travis Scott ft. Drake', 'description': 'Multi-drop madness'},
        {'title': 'Turn Down for What', 'artist': 'DJ Snake & Lil Jon', 'description': 'Pure chaos, perfectly produced'},
        {'title': 'Pump It', 'artist': 'Black Eyed Peas', 'description': 'Classic getting-ready banger'},
        {'title': 'Power', 'artist': 'Kanye West', 'description': 'Epic orchestral swagger'},
        {'title': 'Lose Yourself', 'artist': 'Eminem', 'description': 'The ultimate focus and fire song'},
    ],
    'chill': [
        {'title': 'Ocean Drive', 'artist': 'Duke Dumont', 'description': 'Deep house with a golden sunset feel'},
        {'title': 'Midnight City', 'artist': 'M83', 'description': 'Atmospheric synth-pop for night drives'},
        {'title': 'Electric Feel', 'artist': 'MGMT', 'description': 'Laid-back psychedelic groove'},
        {'title': 'Ribs', 'artist': 'Lorde', 'description': 'Introspective bedroom pop'},
        {'title': 'Sweater Weather', 'artist': 'The Neighbourhood', 'description': 'Moody indie pop with nostalgic warmth'},
        {'title': 'Thinkin Bout You', 'artist': 'Frank Ocean', 'description': 'Ethereal R&B for quiet moments'},
    ],
    'sad': [
        {'title': 'Someone Like You', 'artist': 'Adele', 'description': 'Piano ballad built for cathartic crying'},
        {'title': 'Fix You', 'artist': 'Coldplay', 'description': 'Builds from quiet comfort to an emotional peak'},
        {'title': 'Let Her Go', 'artist': 'Passenger', 'description': 'Folk reflection on taking things for granted'},
        {'title': 'Skinny Love', 'artist': 'Bon Iver', 'description': 'Raw indie folk about a failing relationship'},
        {'title': 'Liability', 'artist': 'Lorde', 'description': 'Stripped-back piano vulnerability'},
        {'title': 'The Night Will Always Win', 'artist': 'Manchester Orchestra', 'description': 'Anthemic sadness with quiet intensity'},
    ],
    'focus': [
        {'title': 'Strobe', 'artist': 'Deadmau5', 'description': '10 minutes of evolving progressive house'},
        {'title': 'Comptine d\'un autre ete', 'artist': 'Yann Tiersen', 'description': 'Delicate piano minimalism from Amelie'},
        {'title': 'Experience', 'artist': 'Ludovico Einaudi', 'description': 'Cinematic piano that clears the mind'},
        {'title': 'Divenire', 'artist': 'Ludovico Einaudi', 'description': 'Flowing classical piano with orchestra'},
        {'title': 'Intro', 'artist': 'The xx', 'description': 'Minimal guitar instrumental for deep work'},
        {'title': 'Floe', 'artist': 'Philip Glass', 'description': 'Repetitive minimalist composition for sustained focus'},
    ],
    'party': [
        {'title': 'Levitating', 'artist': 'Dua Lipa', 'description': 'Disco pop made for dancing all night'},
        {'title': 'One More Time', 'artist': 'Daft Punk', 'description': 'House anthem that never gets old'},
        {'title': 'Shape of You', 'artist': 'Ed Sheeran', 'description': 'Tropical pop groove for any dance floor'},
        {'title': 'Uptown Funk', 'artist': 'Mark Ronson ft. Bruno Mars', 'description': 'Retro funk guaranteed to get everyone moving'},
        {'title': 'Blurred Lines', 'artist': 'Robin Thicke ft. T.I.', 'description': 'Motown-influenced pop funk'},
        {'title': 'Can\'t Stop the Feeling', 'artist': 'Justin Timberlake', 'description': 'Feel-good pop made for Trolls but works everywhere'},
    ],
    'workout': [
        {'title': 'Till I Collapse', 'artist': 'Eminem', 'description': 'Relentless hip hop drive for pushing your limits'},
        {'title': 'Eye of the Tiger', 'artist': 'Survivor', 'description': 'Classic training montage rock'},
        {'title': 'Power', 'artist': 'Kanye West', 'description': 'Orchestral samples over hard 808s'},
        {'title': 'Stronger', 'artist': 'Kanye West', 'description': 'Daft Punk sample turned motivational anthem'},
        {'title': 'Can\'t Hold Us', 'artist': 'Macklemore & Ryan Lewis', 'description': 'High-energy rap with an unstoppable build'},
        {'title': 'Animals', 'artist': 'Martin Garrix', 'description': 'Big room drop that hits like a HIIT interval'},
    ],
}

# ── Artist Info ───────────────────────────────────────────────────────────────

ARTIST_INFO = {
    'Taylor Swift': {
        'genre': 'Pop / Country',
        'known_for': 'Country-to-pop crossover, confessional songwriting, album eras',
        'fun_fact': 'She began writing songs at age 12 and signed her first record deal at 14',
        'top_songs': ['Shake It Off', 'Blank Space', 'Love Story', 'Anti-Hero', 'All Too Well'],
    },
    'Drake': {
        'genre': 'Hip Hop / R&B',
        'known_for': 'Sensitive rap, Toronto pride, OVO Sound, chart domination',
        'fun_fact': "Before music Drake was an actor on the Canadian TV show 'Degrassi'",
        'top_songs': ['Gods Plan', 'One Dance', 'Hotline Bling', 'Started from the Bottom', 'In My Feelings'],
    },
    'Kendrick Lamar': {
        'genre': 'Hip Hop',
        'known_for': 'Lyrical complexity, social commentary, Pulitzer Prize winner',
        'fun_fact': 'He is the first non-classical/jazz musician to win the Pulitzer Prize for Music',
        'top_songs': ['HUMBLE.', 'Swimming Pools', 'Alright', 'Money Trees', 'DNA.'],
    },
    'Dua Lipa': {
        'genre': 'Pop / Dance',
        'known_for': 'Disco-pop revival, Future Nostalgia era, fashion icon',
        'fun_fact': 'She grew up in Kosovo and moved to London at 15 to pursue music',
        'top_songs': ['Levitating', 'Dont Start Now', 'Physical', 'New Rules', 'One Kiss'],
    },
    'The Weeknd': {
        'genre': 'R&B / Pop',
        'known_for': '80s synthwave influence, dark R&B themes, Super Bowl halftime',
        'fun_fact': 'His entire discography connects as one continuous story arc',
        'top_songs': ['Blinding Lights', 'The Hills', 'Starboy', 'Save Your Tears', 'Die For You'],
    },
    'Billie Eilish': {
        'genre': 'Pop / Alternative',
        'known_for': 'Whisper-vocals, dark minimalist production, gen-Z icon',
        'fun_fact': 'She and her brother Finneas wrote and produced her debut album entirely in his bedroom',
        'top_songs': ['Bad Guy', 'Happier Than Ever', 'Ocean Eyes', 'lovely', 'Therefore I Am'],
    },
    'Daft Punk': {
        'genre': 'Electronic / House',
        'known_for': 'Robot personas, pioneering French house, Get Lucky, Random Access Memories',
        'fun_fact': 'They almost never appeared without their robot helmets in public after 1999',
        'top_songs': ['One More Time', 'Get Lucky', 'Around the World', 'Harder Better Faster Stronger', 'Instant Crush'],
    },
    'Queen': {
        'genre': 'Rock',
        'known_for': 'Bohemian Rhapsody, Freddie Mercury\'s voice, stadium anthems',
        'fun_fact': 'Freddie Mercury had a four-octave vocal range',
        'top_songs': ['Bohemian Rhapsody', 'We Will Rock You', 'We Are the Champions', "Don't Stop Me Now", 'Somebody to Love'],
    },
    'Beyonce': {
        'genre': 'R&B / Pop',
        'known_for': 'Lemonade visual album, Destiny\'s Child roots, Renaissance era',
        'fun_fact': 'She holds the record for the most Grammy wins by any artist',
        'top_songs': ['Crazy in Love', 'Formation', 'Halo', 'Irreplaceable', 'Single Ladies'],
    },
    'Avicii': {
        'genre': 'Electronic / House',
        'known_for': 'Progressive house, Levels, folk-EDM fusion, Wake Me Up',
        'fun_fact': "He made his breakthrough with 'Levels' at age 21",
        'top_songs': ['Levels', 'Wake Me Up', 'Hey Brother', 'Without You', 'The Nights'],
    },
}

# ── New Releases List (manually curated — update each week) ──────────────────

NEW_RELEASES = [
    {'title': 'Espresso', 'artist': 'Sabrina Carpenter', 'description': 'Witty retro-pop summer anthem'},
    {'title': 'Feather', 'artist': 'Sabrina Carpenter', 'description': 'Breezy pop with clever self-confidence'},
    {'title': 'Please Please Please', 'artist': 'Sabrina Carpenter', 'description': 'Guitar-pop with relatable romantic anxiety'},
    {'title': 'Birds of a Feather', 'artist': 'Billie Eilish', 'description': 'Tender love song with minimalist production'},
    {'title': 'Lunch', 'artist': 'Billie Eilish', 'description': 'Playful indie-pop with infectious energy'},
    {'title': 'Good Luck, Babe!', 'artist': 'Chappell Roan', 'description': 'Theatrical pop about unresolved feelings'},
    {'title': 'Hot to Go!', 'artist': 'Chappell Roan', 'description': 'Glam rock-pop anthem and crowd favourite'},
    {'title': 'Pink Pony Club', 'artist': 'Chappell Roan', 'description': 'Disco-pop about following your dream'},
    {'title': 'Die With A Smile', 'artist': 'Lady Gaga & Bruno Mars', 'description': 'Soulful duet ballad from two pop icons'},
    {'title': 'APT.', 'artist': 'ROSÉ & Bruno Mars', 'description': 'K-pop meets pop-funk in a high-energy crossover'},
]

# ── Bingo Song Pool ───────────────────────────────────────────────────────────

BINGO_SONG_POOL = [
    'Bohemian Rhapsody', 'Blinding Lights', 'Shape of You', 'Levitating', 'Bad Guy',
    'Humble', 'Gods Plan', 'Sicko Mode', 'One More Time', 'Levels', 'Animals',
    'Mr Brightside', 'Smells Like Teen Spirit', 'Sweet Dreams', 'Rolling in the Deep',
    'Shake It Off', 'Sorry', 'Wrecking Ball', 'We Found Love', 'Titanium',
    'Wake Me Up', 'Titanium', 'Dont You Worry Child', 'Turn Down for What', 'Lean On',
    'Uptown Funk', 'Can Cant Stop the Feeling', 'Happy', 'Counting Stars', 'Radioactive',
    'Demons', 'Pompeii', 'Ho Hey', 'Home', 'Let Her Go',
    'Thinking Out Loud', 'Photograph', 'Perfect', 'Castle on the Hill', 'Galway Girl',
    'Closer', 'Something Just Like This', 'Don Start Now', 'Physical', 'New Rules',
    'We Will Rock You', 'We Are the Champions', 'Somebody to Love', 'Radio Ga Ga',
    'Eye of the Tiger', 'Africa', 'Take on Me', 'Never Gonna Give You Up', 'Girls Just Wanna Have Fun',
]
